spring:
  application:
    name: AFT

aft:
  protocol: native
  location: "Charite, Berlin"
  remote-locations:
    - name: "Test2"
      url: "https://localhost:8091"
  openehr:
    base-url: http://localhost:8090/ehrbase/
    security:
      type: basic
      user:
        name: myuser
        password: myPassword432
  min-hits: 10

beam:
  proxy-url: http://localhost:8081/
  proxy-id: "proxy1.broker"
  app-secret: "App1Secret"

server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always


logging:
  file:
    name: ./logs/aft.log
  level:
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: DEBUG
    root: info
    org:
      springframework:
        boot: error
        nodeValue: error
      hibernate:
        type:
          descriptor:
            sql:
              basicbinder: TRACE
  logback:
    rollingpolicy:
      max-history: '20'
      max-file-size: 100MB

security.enable-csrf: false
