aft:
  openehr:
    base-url: http://localhost:8080/ehrbase/
    security:
      type: basic
      user:
        name: myuser
        password: myPassword432

server:
  port: 8081
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/keystore.p12
    key-store-password: changeit
    protocol: TLS
    enabled-protocols: TLSv1.2
  error:
    include-binding-errors: always
    include-message: always


spring:
  application:
    name: AFT

logging:
  file:
    name: ./logs/aft.log
  level:
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: DEBUG
    root: info
    org:
      springframework:
        boot: error
        nodeValue: error
      hibernate:
        type:
          descriptor:
            sql:
              basicbinder: TRACE
  logback:
    rollingpolicy:
      max-history: '20'
      max-file-size: 100MB

security.enable-csrf: false
