aft:
  openehr:
    base-url: http://localhost:8080/ehrbase/
    security:
      type: basic
      user:
        name: myuser
        password: myPassword432

server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always

spring:
  application:
    name: AFT

logging:
  file:
    name: ./logs/omopbridge.log
  level:
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: DEBUG
    root: info
    org:
      springframework:
        boot: error
        nodeValue: error
      hibernate:
        type:
          descriptor:
            sql:
              basicbinder: TRACE
  logback:
    rollingpolicy:
      max-history: '20'
      max-file-size: 100MB