#docker-compose-full.yml
services:
  ehrbase:
    image: ehrbase/ehrbase:next
    ports:
      - 8080:8080
    networks:
      - ehrbase-net
    environment:
      DB_URL: jdbc:postgresql://ehrdb:5432/ehrbase
      DB_USER_ADMIN: ehrbase
      DB_PASS_ADMIN: ehrbase
      SECURITY_AUTHTYPE: BASIC
      SECURITY_AUTHUSER: myuser
      SECURITY_AUTHPASSWORD: myPassword432
      SECURITY_AUTHADMINUSER: myadmin
      SECURITY_AUTHADMINPASSWORD: mySuperAwesomePassword123
      DB_USER: ehrbase_restricted
      DB_PASS: ehrbase_restricted
    depends_on:
      ehrdb:
        condition: service_healthy
    restart: on-failure

  ehrdb:
    image: ehrbase/ehrbase-postgres:latest
    ports:
      - 5432:5432
    networks:
      - ehrbase-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      EHRBASE_USER_ADMIN: ehrbase
      EHRBASE_PASSWORD_ADMIN: ehrbase
      EHRBASE_USER: ehrbase_restricted
      EHRBASE_PASSWORD: ehrbase_restricted
    volumes:
      - ehrdb-pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: "pg_isready -h localhost -U $$POSTGRES_USER"
      interval: 10s
      timeout: 5s
      retries: 70

  aft:
    image: aft:latest
    ports:
      - 8091:8081
    environment:
      AFT_OPENEHR_BASE-URL: http://ehrbase:8080/ehrbase/
    networks:
      - ehrbase-net
    depends_on:
      - ehrbase2
      - ehrdb2

  ehrbase2:
    image: ehrbase/ehrbase:next
    ports:
      - 8090:8080
    networks:
      - ehrbase-net
    environment:
      DB_URL: jdbc:postgresql://ehrdb2:5433/ehrbase
      DB_USER_ADMIN: ehrbase
      DB_PASS_ADMIN: ehrbase
      SECURITY_AUTHTYPE: BASIC
      SECURITY_AUTHUSER: myuser
      SECURITY_AUTHPASSWORD: myPassword432
      SECURITY_AUTHADMINUSER: myadmin
      SECURITY_AUTHADMINPASSWORD: mySuperAwesomePassword123
      DB_USER: ehrbase_restricted
      DB_PASS: ehrbase_restricted
    depends_on:
      - ehrdb2
    restart: on-failure

  ehrdb2:
    image: ehrbase/ehrbase-postgres:latest
    ports:
      - 5433:5433
    networks:
      - ehrbase-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      EHRBASE_USER_ADMIN: ehrbase
      EHRBASE_PASSWORD_ADMIN: ehrbase
      EHRBASE_USER: ehrbase_restricted
      EHRBASE_PASSWORD: ehrbase_restricted
    command: -p 5433
    volumes:
      - ehrdb2-pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: "pg_isready -h localhost -U $$POSTGRES_USER"
      interval: 10s
      timeout: 5s
      retries: 70

networks:
  ehrbase-net: {}

volumes:
  ehrdb-pgdata:
  ehrdb2-pgdata: